### ISSUE TITLE
help

### ISSUE THREAD

**Issue by sansanmutouren** [liangs111/tensor_holography#11]
PS E:\tensor_holography-main> python main.py --validate-mode
2023-08-18 17:24:13.868982: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operation
s.
Traceback (most recent call last):
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "main.py", line 877, in <module>
    tensor_holo_model.validate()
  File "main.py", line 555, in validate
    _, _, validate_handle, handle, rgbd, holo_in, amp_in, phs_in, holo_out, amp_out, phs_out = self._setup_train()
  File "main.py", line 198, in _setup_train
    test_handle = self.sess.run(test_iterator.string_handle())
AttributeError: 'OwnedIterator' object has no attribute 'string_handle'
 what system do you use? why i can't get the result

**Comment by Huaifeng-xd** [comment]
Linux.  
![image](https://github.com/liangs111/tensor_holography/assets/50742670/01a831cc-29c9-44e3-b0ae-288a537b4c02)
these contents could be found in  README.md
